import csv
import re
import operator

err_dict = {}
user_dict = {}

#The ranking of errors generated by the system
with open('syslog.log') as file:
    for line in file:
        err_line = re.search(r"ERROR\s([\w\s]*)", line)
        if err_line:
            if err_line.group(1).strip() in err_dict:
                err_dict[err_line.group(1).strip()] += 1
            else:
              err_dict[err_line.group(1).strip()] = 1
        else:
          pass
sort_err_dict = dict(sorted(err_dict.items(), key=operator.itemgetter(1), reverse=True))

print(sort_err_dict)